name: Daily Draw

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget -N https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | cut -d. -f1-3)/chromedriver_linux64.zip || true
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run daily draw bot
        run: python draw_bot.py

      - name: Commit log file
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add log.txt
          git commit -m "Update log.txt from GitHub Actions" || echo "No changes to commit"
          git push

permissions:
  contents: write