name: Keep Website Alive

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Make a GET request to the website
        run: |
          curl -X GET https://pdfiledit.onrender.com/

      - name: Log the success to log.txt
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') - Website Ping Success" >> log.txt

      - name: Commit and push log.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "Update log.txt with ping success" || echo "No changes to commit"
          git push
